BENCHMARK_DATA = "/benchmark/data"
BENCHMARK_DATA_MODEL = f"{BENCHMARK_DATA}/model"
BENCHMARK_DATA_DATASET = f"{BENCHMARK_DATA}/dataset"
BENCHMARK_DATA_ANNOTATION = f"{BENCHMARK_DATA}/annotation"
BENCHMARK_JOB = "/benchmark/job"

DEVICE = "/device"
SENSOR = "/sensor"
